-- Migration script to update database schema for WSO2 IS 7.1.0
-- This script adds missing tables and columns required by WSO2 Identity Server 7.1.0

USE WSO2AM_DB;

-- Add missing columns to IDP_AUTHENTICATOR table
ALTER TABLE IDP_AUTHENTICATOR
ADD COLUMN IF NOT EXISTS IMAGE_URL VARCHAR(1024) AFTER NAME,
ADD COLUMN IF NOT EXISTS DESCRIPTION VARCHAR(1024) AFTER IMAGE_URL,
ADD COLUMN IF NOT EXISTS DEFINED_BY VARCHAR(25) NOT NULL DEFAULT 'SYSTEM' AFTER DISPLAY_NAME,
ADD COLUMN IF NOT EXISTS AUTHENTICATION_TYPE VARCHAR(25) NOT NULL DEFAULT 'STANDARD' AFTER DEFINED_BY;

-- Create API_RESOURCE table
CREATE TABLE IF NOT EXISTS API_RESOURCE (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    IDENTIFIER VARCHAR(255) NOT NULL,
    TENANT_ID INT,
    DESCRIPTION VARCHAR(255),
    TYPE VARCHAR(255) NOT NULL,
    REQUIRES_AUTHORIZATION BOOLEAN NOT NULL,
    UNIQUE KEY (CURSOR_KEY)
) DEFAULT CHARACTER SET latin1 ENGINE INNODB;

-- Create SCOPE table
CREATE TABLE IF NOT EXISTS SCOPE (
    ID CHAR(36) NOT NULL PRIMARY KEY,
    CURSOR_KEY INTEGER NOT NULL AUTO_INCREMENT,
    API_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    TENANT_ID INT,
    DESCRIPTION VARCHAR(300),
    UNIQUE KEY (CURSOR_KEY),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET latin1 ENGINE INNODB;

-- Create API_RESOURCE_PROPERTY table
CREATE TABLE IF NOT EXISTS API_RESOURCE_PROPERTY (
    ID INTEGER AUTO_INCREMENT,
    API_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT API_RESOURCE_PROPERTY_CONSTRAINT UNIQUE (API_ID, NAME),
    FOREIGN KEY (API_ID) REFERENCES API_RESOURCE(ID) ON DELETE CASCADE
) DEFAULT CHARACTER SET latin1 ENGINE INNODB;

-- Mark migration as complete
INSERT INTO IDN_BASE_TABLE (PRODUCT_NAME)
VALUES ('WSO2 IS 7.1.0 Migration Complete')
ON DUPLICATE KEY UPDATE PRODUCT_NAME = PRODUCT_NAME;
